### ISSUE TITLE
Android Device Orientation Support

### ISSUE THREAD

**Issue by YoussefHachicha** [swapnil-musale/KDeviceInfo#12]
can you add get screen rotation and other things like change status bar color also how did you get the Initializer i wasn't able to get it

**Comment by swapnil-musale** [comment]
Right now you can access device orientation on through ```iosInfo``` object. 
Will add support for android version in upcoming release.

**Comment by swapnil-musale** [comment]
Device orientation support has been added in v0.0.5 🚀
